FROM kiyoon/cudaopencv:cuda9.0-cudnn7-gpuarch6.1-OCV3.4-python2

LABEL maintainer="Kiyoon Kim <yoonkr33@gmail.com>"

# Install python2 ML modules
RUN pip --no-cache-dir install \
        keras_applications \
        keras_preprocessing \
        keras==2.1.6 \
        sklearn

# Install python3 ML modules
RUN pip3 --no-cache-dir install \
        Pillow \
        h5py \
        keras_applications \
        keras_preprocessing \
        keras==2.1.6 \
        matplotlib \
        numpy \
        pandas \
        scipy \
        sklearn 

# Install TensorFlow GPU version.
ADD ./cuda9.0-cudnn7.0-nccl2.2-arch6.1/ /tf/
RUN pip3 --no-cache-dir install /tf/tensorflow-1.7.1-cp35-cp35m-linux_x86_64.whl && \
    pip --no-cache-dir install /tf/tensorflow-1.7.1-cp27-cp27mu-linux_x86_64.whl && \
    rm -rf /tf

# RUN ln -s -f /usr/bin/python3 /usr/bin/python#

# Set up our notebook config.
COPY jupyter_notebook_config.py /root/.jupyter/

# Copy sample notebooks.
COPY notebooks /notebooks

# Jupyter has issues with being run directly:
#   https://github.com/ipython/ipython/issues/7062
# We just add a little wrapper script.
COPY run_jupyter.sh /

# For CUDA profiling, TensorFlow requires CUPTI.
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH
ENV PATH /usr/local/cuda/bin:$PATH

# TensorBoard
EXPOSE 6006
# IPython
EXPOSE 8888

#WORKDIR "/notebooks"

#CMD ["/run_jupyter.sh", "--allow-root"]
